version: '2'

services:
  data-volumes:
    image: busybox
    tty: true
    stdin_open: true
    volumes:
      - "./tools/data:/data:rw"
      - "./tools/data/rethinkdb:/data/rethinkdb:rw"
      - "./docs/logs/rethinkdb:/var/logs/rethinkdb:rw"
  db:
    image: strues/rethinkdb
    ports:
     - "8080:8080/tcp"
     - "28015:28015/tcp"
     - "29015:29015/tcp"
    expose:
      - "8080"
      - "28015"
      - "29015"
    volumes_from:
      - data-volumes
    networks:
      - splat

  splatter:
    build: ./
    depends_on:
        - db
    ports:
      - 3000:3000/tcp
      - 5858:5858/tcp
    networks:
      - splat
networks:
  splat:
    driver: bridge
